services:
  - type: web
    name: marin-kitagawa-md
    env: docker
    plan: free
    dockerCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MONGODB
        sync: false
      - key: PREFIX
        value: .
      - key: PACKNAME
        value: Marin-MD
      - key: AUTHOR
        value: Sten-X
      - key: MODS
        sync: false
